Fix: Expansion of pr_body with breaking characters
repo-sync/pull-request pull request #89
Opened 2022-05-16 21:08 UTC by math-breault

Issue: #27 

The expansion of the `pr_body` parameter from the `INPUT_PR_BODY` variable was not being properly escaped for use as an argument with `hub`.  This caused `"` characters to end the command and the next character to be interpreted by bash, resulting in failures. This was also causing code blocks to disappear from the PR body.

The fix is the one suggested by @wei in https://github.com/repo-sync/pull-request/issues/27#issuecomment-650314540 . It uses the `Q` operator for expanding the `INPUT_PR_BODY` variable. Details on the expansion operator can be found here: https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html.

2022-09-30 06:17 UTC, krtschmr approved these changes

2022-09-30 06:56 UTC, krtschmr commented
this would not fix multiline body issues.


<img width="566" alt="image" src="https://user-images.githubusercontent.com/13366714/193209181-2dcbc526-d499-4e1d-850f-3df7953eaff5.png">

branch i used: https://github.com/dcflw/pull-request/commits/master

2022-10-02 19:16 UTC, wei requested changes
See comment above

2022-10-31 21:50 UTC, wei commented
@math-breault do you have capacity to take a look?

2022-11-01 15:07 UTC, wei commented
Seems to be working with `\n` in #83 #103. Closing for now.

2022-11-01 15:07 UTC, closed without merging

2022-11-02 21:17 UTC, krtschmr commented
not fixed for us. using \n inside the string. 


<img width="450" alt="image" src="https://user-images.githubusercontent.com/13366714/199604286-5cb3149e-ef8b-44c4-9add-55e6c0ebd158.png">

2022-11-02 21:21 UTC, krtschmr commented
@wei  let's reopen this, unless i did something wrong :-)

2022-11-02 22:49 UTC, wei commented
> @wei  let's reopen this, unless i did something wrong :-)

Could you try adding \nNewLine after pr_body }}